import { StyleSheet } from "react-native";

const Styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "white",
  },
  locationView: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 16,
    backgroundColor: "white",
    // shadowColor: "#000000",
    // shadowOffset: {
    //   width: 0,
    //   height: 4,
    // },
    // shadowOpacity: 0.19,
    // shadowRadius: 5.62,
    // elevation: 6,
  },
  cartCount: {
    backgroundColor: "red",
    borderRadius: 50,
    textAlign: "center",
    fontSize: 12,
    fontWeight: "bold",
    color: "white",
    position: "absolute",
    right: -5,
    top: -8,
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  searchView: {
    borderColor: "#ced4da",
    borderWidth: 2,
    borderRadius: 6,
    height: 50,
    padding: 8,
    flexDirection: "row",
  },
  searchFilter: {
    flex: 1,
    alignItems: "center",
    width: 30,
    alignContent: "center",
    alignSelf: "center",
    justifyContent: "center",
  },
  imageViewContainer: {
    //f2f2f2
    width: "100%",
    backgroundColor: "#f2f2f2",
    height: "29%",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    justifyContent: "center",
  },
  imageContainer: {
    //margin: 18,
    borderRadius: 18,
    height: "70%",
    width: "90%",
    alignSelf: "center",
  },
  categoriesCards: {
    borderRadius: 8,
    width: 80,
    height: 80,
    backgroundColor: "white",
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.18,
    shadowRadius: 4.59,
    elevation: 5,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 14,
    marginBottom: 16,
  },
  categoriesView: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  categoriesTitle: { color: "black", fontSize: 16, fontWeight: "bold" },
  categoriesViewMore: { color: "#c23d32", fontSize: 16, fontWeight: "bold" },
  categoriesCardsView: {
    marginTop: 8,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  bestsellerContainer: {
    paddingHorizontal: 16,
    backgroundColor: "#f2f2f2",
  },
  bestSellerCardView: {
    borderRadius: 8,
    width: 155,
    height: 180,
    backgroundColor: "white",
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.18,
    shadowRadius: 4.59,
    elevation: 5,
    position: "relative",
    marginRight: 14,
    marginBottom: 16,
    paddingBottom: 12,
  },
  bestsellerCardContainer: {
    marginTop: 8,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  bestsellerImageContainer: {
    height: "80%",
    width: "100%",
    padding: 8,
  },
  bestsellerImage: {
    height: "100%",
    width: "100%",
    borderRadius: 8,
  },
  bestsellerPercentageContainer: {
    backgroundColor: "#c23d32",
    position: "absolute",
    paddingVertical: 2,
    paddingHorizontal: 12,
    borderTopLeftRadius: 12,
    borderBottomRightRadius: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  bestsellerPercentage: {
    color: "white",
    justifyContent: "center",
    marginRight: 3,
  },
  bestsellerText: { color: "white", fontWeight: "600", marginLeft: 3 },
  bestsellerStarContainer: {
    backgroundColor: "black",
    height: 15,
    width: 15,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 6,
    marginRight: 2,
  },
});

export default Styles;
